---
- name: Python関連のパッケージインストール
  apt:
    force_apt_get: yes
    state: latest
    name:
      - python-pip
      - libffi-dev
      - gettext
      - zlib1g-dev
      - libssl-dev
      - libreadline-dev
      - libsqlite3-dev
      - libbz2-dev
      - libncurses5-dev
      - libgdbm-dev
      - liblzma-dev
      - tk-dev
      - zlibc

- name: タイムゾーンを東京に設定
  timezone:
    name: Asia/Tokyo

- block:
    - name: pyenvの存在チェック
      command: test -x {{ home_dir }}/.pyenv/bin/pyenv
      register: pyenv_present
      ignore_errors: yes

    - name: pyenvリポジトリ更新
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: "{{ home_dir }}/.pyenv"
      when: pyenv_present is failed

    - name: pyenv設定追加
      lineinfile:
        dest: "{{ home_dir }}/.bash_profile"
        state: present
        create: yes
        line: "{{ item }}"
      with_items:
        - 'export PYENV_ROOT="$HOME/.pyenv"'
        - 'export PATH="$PYENV_ROOT/bin:$PATH"'
        - 'if command -v pyenv 1>/dev/null 2>&1; then'
        - '  eval "$(pyenv init -)"'
        - 'fi'
      when: pyenv_present is failed

    - name: bash_profile読み込み
      shell: /bin/bash -lc "source ~/.bash_profile"

    - name: Python{{ install_python_version }} インストール
      shell: /bin/bash -lc "pyenv install {{ install_python_version }}"
      when: pyenv_present is failed

    - name: shim更新
      shell: /bin/bash -lc "pyenv rehash"
      when: pyenv_present is failed

    - name: Pythonインターセプタ変更
      set_fact: ansible_python_interpreter={{ home_dir }}/.pyenv/shims/python

    - name: python{{ install_python_version }}のglobal指定
      shell: /bin/bash -lc "pyenv global {{ install_python_version }}"

    - name: Python{{ install_python_version }}のpipアップグレード
      pip:
        name: pip
        state: latest

    - name: Pythonインターセプタ変更
      set_fact: ansible_python_interpreter=/usr/bin/python

  become: yes
  become_user: "{{ user_name }}"
